FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Graffle.FlowEventProcessor.dll"]