FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

#copy csproj
COPY Graffle.FlowEventProcessor.csproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Debug -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
ENV WebhookUrl=${WebhookUrl}
ENV EventId=${EventId}
ENV Verbose=False
ENV MaximumBlockScanRange=200
ENV FlowNode=${FlowNode}
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "Graffle.FlowEventProcessor.dll"]